// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_qm4b_TCttceUGnodVPC8rJBpLlDPAf4',
    appId: '1:1082213832190:web:43b88ab067b8056a7bdcaf',
    messagingSenderId: '1082213832190',
    projectId: 'photobooth-dcd5f',
    authDomain: 'photobooth-dcd5f.firebaseapp.com',
    storageBucket: 'photobooth-dcd5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvHUP5lxVTIszEKETDBn-0WRGqBNdZtP0',
    appId: '1:1082213832190:android:ad0b49a6ec8940457bdcaf',
    messagingSenderId: '1082213832190',
    projectId: 'photobooth-dcd5f',
    storageBucket: 'photobooth-dcd5f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_qm4b_TCttceUGnodVPC8rJBpLlDPAf4',
    appId: '1:1082213832190:web:2c1265830b36edc07bdcaf',
    messagingSenderId: '1082213832190',
    projectId: 'photobooth-dcd5f',
    authDomain: 'photobooth-dcd5f.firebaseapp.com',
    storageBucket: 'photobooth-dcd5f.firebasestorage.app',
  );
}
